# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NodesIdsResponseStates(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'state': 'str',
        'ids': 'str'
    }

    attribute_map = {
        'state': 'state',
        'ids': 'ids'
    }

    def __init__(self, state=None, ids=None):  # noqa: E501
        """NodesIdsResponseStates - a model defined in OpenAPI"""  # noqa: E501

        self._state = None
        self._ids = None
        self.discriminator = None

        if state is not None:
            self.state = state
        if ids is not None:
            self.ids = ids

    @property
    def state(self):
        """Gets the state of this NodesIdsResponseStates.  # noqa: E501


        :return: The state of this NodesIdsResponseStates.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this NodesIdsResponseStates.


        :param state: The state of this NodesIdsResponseStates.  # noqa: E501
        :type: str
        """
        allowed_values = ["Absent", "Alive", "Busy", "Suspected", "Dead", "Absent"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def ids(self):
        """Gets the ids of this NodesIdsResponseStates.  # noqa: E501


        :return: The ids of this NodesIdsResponseStates.  # noqa: E501
        :rtype: str
        """
        return self._ids

    @ids.setter
    def ids(self, ids):
        """Sets the ids of this NodesIdsResponseStates.


        :param ids: The ids of this NodesIdsResponseStates.  # noqa: E501
        :type: str
        """

        self._ids = ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodesIdsResponseStates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
