# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class UserRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'country': 'str',
        'organization': 'str',
        'motivations': 'str',
        'city': 'str',
        'password': 'str',
        'category': 'str',
        'sshkeys': 'list[str]',
        'groups': 'list[str]'
    }

    attribute_map = {
        'first_name': 'firstName',
        'last_name': 'lastName',
        'email': 'email',
        'country': 'country',
        'organization': 'organization',
        'motivations': 'motivations',
        'city': 'city',
        'password': 'password',
        'category': 'category',
        'sshkeys': 'sshkeys',
        'groups': 'groups'
    }

    def __init__(self, first_name=None, last_name=None, email=None, country=None, organization=None, motivations=None, city=None, password=None, category=None, sshkeys=None, groups=None):  # noqa: E501
        """UserRequest - a model defined in OpenAPI"""  # noqa: E501

        self._first_name = None
        self._last_name = None
        self._email = None
        self._country = None
        self._organization = None
        self._motivations = None
        self._city = None
        self._password = None
        self._category = None
        self._sshkeys = None
        self._groups = None
        self.discriminator = None

        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if country is not None:
            self.country = country
        if organization is not None:
            self.organization = organization
        if motivations is not None:
            self.motivations = motivations
        if city is not None:
            self.city = city
        if password is not None:
            self.password = password
        if category is not None:
            self.category = category
        if sshkeys is not None:
            self.sshkeys = sshkeys
        if groups is not None:
            self.groups = groups

    @property
    def first_name(self):
        """Gets the first_name of this UserRequest.  # noqa: E501


        :return: The first_name of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserRequest.


        :param first_name: The first_name of this UserRequest.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UserRequest.  # noqa: E501


        :return: The last_name of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserRequest.


        :param last_name: The last_name of this UserRequest.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this UserRequest.  # noqa: E501


        :return: The email of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserRequest.


        :param email: The email of this UserRequest.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def country(self):
        """Gets the country of this UserRequest.  # noqa: E501


        :return: The country of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this UserRequest.


        :param country: The country of this UserRequest.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def organization(self):
        """Gets the organization of this UserRequest.  # noqa: E501


        :return: The organization of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this UserRequest.


        :param organization: The organization of this UserRequest.  # noqa: E501
        :type: str
        """

        self._organization = organization

    @property
    def motivations(self):
        """Gets the motivations of this UserRequest.  # noqa: E501


        :return: The motivations of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._motivations

    @motivations.setter
    def motivations(self, motivations):
        """Sets the motivations of this UserRequest.


        :param motivations: The motivations of this UserRequest.  # noqa: E501
        :type: str
        """

        self._motivations = motivations

    @property
    def city(self):
        """Gets the city of this UserRequest.  # noqa: E501


        :return: The city of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this UserRequest.


        :param city: The city of this UserRequest.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def password(self):
        """Gets the password of this UserRequest.  # noqa: E501


        :return: The password of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserRequest.


        :param password: The password of this UserRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def category(self):
        """Gets the category of this UserRequest.  # noqa: E501


        :return: The category of this UserRequest.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this UserRequest.


        :param category: The category of this UserRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["Student", "Academic", "Startup", "Business"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"  # noqa: E501
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def sshkeys(self):
        """Gets the sshkeys of this UserRequest.  # noqa: E501


        :return: The sshkeys of this UserRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._sshkeys

    @sshkeys.setter
    def sshkeys(self, sshkeys):
        """Sets the sshkeys of this UserRequest.


        :param sshkeys: The sshkeys of this UserRequest.  # noqa: E501
        :type: list[str]
        """

        self._sshkeys = sshkeys

    @property
    def groups(self):
        """Gets the groups of this UserRequest.  # noqa: E501


        :return: The groups of this UserRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this UserRequest.


        :param groups: The groups of this UserRequest.  # noqa: E501
        :type: list[str]
        """

        self._groups = groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
