# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.models.activate_user_request import ActivateUserRequest  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestActivateUserRequest(unittest.TestCase):
    """ActivateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivateUserRequest(self):
        """Test ActivateUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iotlabclient.client.models.activate_user_request.ActivateUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
