# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.api.monitoring_api import MonitoringApi  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestMonitoringApi(unittest.TestCase):
    """MonitoringApi unit test stubs"""

    def setUp(self):
        self.api = iotlabclient.client.api.monitoring_api.MonitoringApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_profile(self):
        """Test case for delete_profile

        Delete monitoring profile.  # noqa: E501
        """
        pass

    def test_get_profile(self):
        """Test case for get_profile

        Returns monitoring profile.  # noqa: E501
        """
        pass

    def test_get_profiles(self):
        """Test case for get_profiles

        Returns monitoring profiles list.  # noqa: E501
        """
        pass

    def test_modify_profile(self):
        """Test case for modify_profile

        Modify monitoring profile.  # noqa: E501
        """
        pass

    def test_save_profile(self):
        """Test case for save_profile

        Create monitoring profile.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
