# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.models.alias_properties import AliasProperties  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestAliasProperties(unittest.TestCase):
    """AliasProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAliasProperties(self):
        """Test AliasProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iotlabclient.client.models.alias_properties.AliasProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
