# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.api.robots_api import RobotsApi  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestRobotsApi(unittest.TestCase):
    """RobotsApi unit test stubs"""

    def setUp(self):
        self.api = iotlabclient.client.api.robots_api.RobotsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_are_coordinates_reachable(self):
        """Test case for are_coordinates_reachable

        Returns if robots coordinates (eg. ROS points) are reachable  # noqa: E501
        """
        pass

    def test_get_dock_config(self):
        """Test case for get_dock_config

        Returns robots site dock config  # noqa: E501
        """
        pass

    def test_get_map_config(self):
        """Test case for get_map_config

        Returns robots site map config  # noqa: E501
        """
        pass

    def test_get_map_coordinates(self):
        """Test case for get_map_coordinates

        Returns robots map coordinates from ros coordinates.  # noqa: E501
        """
        pass

    def test_get_map_image(self):
        """Test case for get_map_image

        Returns robots site map image  # noqa: E501
        """
        pass

    def test_get_ros_coordinates(self):
        """Test case for get_ros_coordinates

        Returns robots ros coordinates from map coordinates.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
