# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.api.modelmobilitise_api import ModelmobilitiseApi  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestModelmobilitiseApi(unittest.TestCase):
    """ModelmobilitiseApi unit test stubs"""

    def setUp(self):
        self.api = iotlabclient.client.api.modelmobilitise_api.ModelmobilitiseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_user_model_mobility(self):
        """Test case for delete_user_model_mobility

        Delete model mobility  # noqa: E501
        """
        pass

    def test_modify_user_model_mobility(self):
        """Test case for modify_user_model_mobility

        Modify model mobility  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
