# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.api.firmwares_api import FirmwaresApi  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestFirmwaresApi(unittest.TestCase):
    """FirmwaresApi unit test stubs"""

    def setUp(self):
        self.api = iotlabclient.client.api.firmwares_api.FirmwaresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_firmware(self):
        """Test case for delete_firmware

        Delete a user firmware  # noqa: E501
        """
        pass

    def test_get_firmware(self):
        """Test case for get_firmware

        get a stored firmware metadata  # noqa: E501
        """
        pass

    def test_get_firmware_file(self):
        """Test case for get_firmware_file

        get a stored firmware file  # noqa: E501
        """
        pass

    def test_get_firmware_format(self):
        """Test case for get_firmware_format

        Returns firwmare format.  # noqa: E501
        """
        pass

    def test_get_firmwares(self):
        """Test case for get_firmwares

        get a list of stored firmware metadatas  # noqa: E501
        """
        pass

    def test_modify_firmware(self):
        """Test case for modify_firmware

        modify a stored user firmware  # noqa: E501
        """
        pass

    def test_save_firmware(self):
        """Test case for save_firmware

        save a user firmware  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
