# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.api.model_mobilities_api import ModelMobilitiesApi  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestModelMobilitiesApi(unittest.TestCase):
    """ModelMobilitiesApi unit test stubs"""

    def setUp(self):
        self.api = iotlabclient.client.api.model_mobilities_api.ModelMobilitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_user_model_mobility(self):
        """Test case for delete_user_model_mobility

        Delete model mobility  # noqa: E501
        """
        pass

    def test_get_model_mobilities(self):
        """Test case for get_model_mobilities

        Returns models list  # noqa: E501
        """
        pass

    def test_get_model_mobility(self):
        """Test case for get_model_mobility

        Returns model  # noqa: E501
        """
        pass

    def test_get_model_mobility_script(self):
        """Test case for get_model_mobility_script

        Returns model script file  # noqa: E501
        """
        pass

    def test_modify_user_model_mobility(self):
        """Test case for modify_user_model_mobility

        Modify model mobility  # noqa: E501
        """
        pass

    def test_save_user_model_mobility(self):
        """Test case for save_user_model_mobility

        Create model mobility  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
