# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.api.default_api import DefaultApi  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = iotlabclient.client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_firmware_format(self):
        """Test case for get_firmware_format

        Returns firwmare format.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
