# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.models.firmware_alias_associations_firmwareassociations import FirmwareAliasAssociationsFirmwareassociations  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestFirmwareAliasAssociationsFirmwareassociations(unittest.TestCase):
    """FirmwareAliasAssociationsFirmwareassociations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFirmwareAliasAssociationsFirmwareassociations(self):
        """Test FirmwareAliasAssociationsFirmwareassociations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iotlabclient.client.models.firmware_alias_associations_firmwareassociations.FirmwareAliasAssociationsFirmwareassociations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
