# coding: utf-8

"""
    IoT-LAB REST API

    REST API documentation of [IoT-LAB](http://www.iot-lab.info) testbed.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iotlabclient.client
from iotlabclient.client.models.alias_mobility_association import AliasMobilityAssociation  # noqa: E501
from iotlabclient.client.rest import ApiException


class TestAliasMobilityAssociation(unittest.TestCase):
    """AliasMobilityAssociation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAliasMobilityAssociation(self):
        """Test AliasMobilityAssociation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iotlabclient.client.models.alias_mobility_association.AliasMobilityAssociation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
